### ISSUE TITLE
UDP port

### ISSUE THREAD

**Issue by OK1SLM** [Eshco93/dxlAPRS-SHUE#4]
Hi,
I use this script, but the problem is that there is already an added port -J 127.0.0.1:4099, can I use it?

https://github.com/DO2JMG/dxlAPRS_Scripte/blob/main/dxlserver.sh

**Comment by Eshco93** [comment]
That's a question you might want to ask the author of this script. When I look at the script, I can't see any application listening on port 4099. Maybe the UDP JSON output is unused, although it is enabled for sondemod. In that case, you can just modify the port and use the UDP JSON output for dxlAPRS-SHUE.

**Comment by OK1SLM** [comment]
OK Tnx
