### ISSUE TITLE
I can't update the repo.

### ISSUE THREAD

**Issue by sp3wxh** [Eshco93/dxlAPRS-SHUE#5]
Hello. 

I can't update the repo. The 'git pull' command fails with the error: 'fatal: bad object refs/heads/main'.

dxl@raspberrypi:~/dxlAPRS-SHUE $ git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
Rozpakowywanie obiektów: 100% (9/9), 9.71 KiB | 2.43 MiB/s, gotowe.
fatal: bad object refs/heads/main
error: https://github.com/Eshco93/dxlAPRS-SHUE nie wysłał wszystkich potrzebnych obiektów

dxl@raspberrypi:~/dxlAPRS-SHUE $

![Zrzut ekranu 2024-08-26 o 21 11 56](https://github.com/user-attachments/assets/6f2b5b67-cfb2-410b-a3c3-2375f11d626f)

**Comment by Eshco93** [comment]
First of all, I would like to apologize for replying so late. To me, this looks more like a problem with Git and less like a problem with the application. Or am I wrong?

**Comment by sp3wxh** [comment]
OK. I did this:
- I deleted the entire dxlAPRS-SHUE/ directory,
- I downloaded the repo again.

It works.
![Zrzut ekranu 2024-10-20 o 12 24 12](https://github.com/user-attachments/assets/bdd3ff3e-e274-4534-b9af-9ca386234b18)
